apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
    name: kibana
    namespace: NAMESPACE
spec:
    version: KIBANA_VERSION
    count: 1
    http:
      # tls:
      #   selfSignedCertificate:
      #     subjectAltNames:
      #       - dns: custom.dns.com
      service:
            spec:
                type: LoadBalancer
    config:
        elasticsearch.requestHeadersWhitelist:
        - authorization
    elasticsearchRef:
        name: escluster
        # namespace: es
    podTemplate:
        metadata:
            labels:
                app: kibana
        spec:
            containers:
            - name: kibana
            nodeSelector:
              app: elasticsearch
